### ISSUE TITLE
Provide a "condensed stencil.yml" file that just lists operations

### ISSUE THREAD

**Issue by aldrichtr** [aldrichtr/stencil#30]
Something like:
```yaml
- tree:
#...
- copy:
#...
```

How would the user call it?  Maybe specify the file path to invoke-stencil ?
